services:
  redis:
    image: redis:7-alpine
    container_name: weather-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  weather-api:
    build: .
    container_name: weather-api
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
    restart: unless-stopped 